### ISSUE TITLE
msw doesn't seem to actually work with this setup

### ISSUE THREAD

**Issue by johncantrell97** [remix-run/grunge-stack#25]
Not sure if I'm doing something wrong but when I run `npm run dev` I see that the mocks are being started and loaded with this log `console.info("🔶 Mock server running");`

However, if I change onUnhandledRequest to "error" like this `server.listen({ onUnhandledRequest: "error" });` I never see any errors or logs about unhandled requests even though I'm definitely making requests to Stripe.

I've tried all sorts of things to debug but can't make progress.  

Any ideas? 

edit: seems like the sanbox is likely starting separate node processes to run the lambdas which MSW won't see.

**Comment by kentcdodds** [comment]
Ah, that's a bummer. I tested it in the other stacks but not this one. We may need to be a bit more invasive by requiring the mocks in app code 😬

@tbeseda can you confirm that [this](https://github.com/remix-run/grunge-stack/blob/23fae6363760809ccf813238f6eda9d77d008d5b/dev.js#L5) will run in a different node process from the app? If so, we may need to move that require into `app/entry.server.ts` during development.

Would be better if there were a way to do a `--require` sort of thing with arc directly so we don't have to put it in app code.

**Comment by johncantrell97** [comment]
Yeah, I'm playing around with running msw in server.ts and it seems to work okay.

**Comment by johncantrell97** [comment]
Can confirm it does work if you start the server in `app/entry.server.ts` but it feels like it really slows every request down quite a bit.  Also saw some issues with a 3rd party library that was using axios to post.

**Comment by tbeseda** [comment]
Correct, Architect will run each function execution in a new process. It does use the same environment from the root project/package.json, but doesn't inherit from the parent process. This behavior is important to emulating how Lambda will run the function in isolation on AWS.
Obviously `msw` is really helpful for mocking APIs that a function would interact with, but I'm not sure how it could be wrapped around a function in Sandbox. A plugin might help, but I think no matter what it has to be started each time a request is made since there are no long running processes.

**Comment by gnllucena** [comment]
any luck trying to make debugger work in grunge stack @eXigentCoder?

**Comment by pcbl** [comment]
I am also facing challenges to debug in grunge stack. Anyonbe knows of some advices to make it work?
