### ISSUE TITLE
Tests not passing 

### ISSUE THREAD

**Issue by JoaoGomes5** [remix-run/grunge-stack#34]
Hi, I'm really excited about Stacks

But I tried to deploy the grunge Stack as it says in the README itself and after installing the tests idoesn't pass.

 **Tests that not pass**
    1) should allow you to register and login
    2) should allow you to make a note

**Gist with the errors**
https://gist.github.com/JoaoGomes5/7cfa976ae9672ab5e7bd4c255ec7677a

I followed the tutorial video [](https://www.youtube.com/watch?v=J9sHle5Q8ME) and it gives me an error right at the beginning, I don't understand why.

I already tried to create new projects and all of them did not pass the tests.

Thanks and have a great day!

**Comment by salper** [comment]
I've been using remix for a while now, and the `Buffer is not defined` issue has been there for a while. It's coming from the `unstable_*` multipart feature that has been added this year. Curiously, the `unstable_parseMultipartFormData`, which relies on `busboy`, which loads `buffer`, is bundled in the client dist while not being used at all in the routes, so something must be wrong in the `esbuild` config.

**Comment by salper** [comment]
What's weird is that `unstable_createMemoryUploadHandler` is bundled when `unstable_createFileUploadHandlerfrom` is not, so that could be a clue.

**Comment by JoaoGomes5** [comment]
Yeah, it's weird because I literally just cloned and installed the dependencies. And then I run the tests and they don't work

**Comment by salper** [comment]
Just dug into it. What I've found is that a simple `rm -rf public/build && npm run build:remix` seems to clear the issue, as the client bundle seems clean after that, so I wonder if it's not the `remix-init` of the stack that's doing something differently. Trying to confirm that for now.

**Comment by salper** [comment]
As said earlier, the problem has been there since the introduction of the multipart feature (don't know why I've said it could be the `remix-init` of the stack 🤭 ). I've tried on a baremetal install (architect+typescript), and the issue occurs between the `remix watch` and the `remix build`:
- `remix build` -> client bundle is clean
- `remix watch` -> client bundle has occurrences of `unstable_createMemoryUploadHandler `

**Comment by salper** [comment]
Ah! Ah! It's actually normal to have occurrences of `unstable_createMemoryUploadHandler` in the build folder, as it's due to the source map generation 😱 . So the client warning is actually be due to the stack setup, as I have an occurence in a generated js chunk using `remix watch` and not `remix build`.

**Comment by salper** [comment]
I think I've got something now. Commenting the `routes` entry in the `remix.config.js` provides a clean browser build. It makes sense as the `cypress/support/test-routes/create-user.ts` is included via the `routes` attribute only when `process.env.NODE_ENV` is not `production`. So my first guess is that routes included via the `routes` entry are not pruned (or tree shaken) properly, and remix is fully loaded inside (`routes` entry commented, the chunk is only `176K` while not commented, the chunk weighs `1.1M`).

**Comment by JoaoGomes5** [comment]
Thanks you very much @salper for the reply!
